---
name: Docker build and publish

on:
  # cron job to trigger the build on any push to main
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Get today's date
      run: echo "::set-output name=day::$(date +'%Y%m%d')"

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
        push: true
        tags: aleksanderbl:cv:${{ steps.day.outputs.day }}

        # aleksanderbl\cv:latest
    # - name: Build and push
    #   uses: docker/build-push-action@v4
    #   with:
    #     platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
    #     context: "{{defaultContext}}:cv_nginx/"
    #     push: true
    #     tags: aleksanderbl/cv_nginx:latest,aleksanderbl/cv_nginx:${{ steps.day.outputs.day }}

    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.day.outputs.day }}
        name: "CV - ${{ steps.day.outputs.day }}"
        body: |
          # Aleksander Bang-Larsens CV
          Opdateret pr. ${{ steps.day.outputs.day }}

